import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Main from "@/components/Main";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bookmark Navigation",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="dark:bg-dark-900 flex h-screen flex-col bg-gray-100 transition-colors duration-300">
      <Header></Header>
      <Main />
      <Footer></Footer>
    </div>
  );
}
